### ISSUE TITLE
Password change doesn't work

### ISSUE THREAD

**Issue by kachok** [amida-tech/dre-frontend#27]
Created new account, tried to change password
Red error message

**Comment by igiware** [comment]
DRE-services returns "400 - Old Password doesn't matchfalse"
posted data is correct {old: "testtest", new: "test1234"}

**Comment by kachok** [comment]
@chaldon can you take a look at backend service

**Comment by kachok** [comment]
I think we pushed update to DRE-services to fix it, will verify

**Comment by UglyEugen** [comment]
still not working, but with a different symptoms
OPTIONS /api/v1/changepassword 200 4.741 ms - 4
changepassword API: { old: 'testtest', new: 'test1234' }
[ { _id: 5614b4f1281b371d138aeebc, username: 'test', __v: 0 } ]
user found
->>>> null false { message: 'Authentication not possible. No salt value stored in mongodb collection!' }
auth err false { message: 'Authentication not possible. No salt value stored in mongodb collection!' }
POST /api/v1/changepassword 400 6.204 ms - 31

while "salt" is present in DB
-> db.users.find({ "username" : "test" })
{ "_id" : ObjectId("5614b4f1281b371d138aeebc"), "salt" : "ad8161d54dc767263215550291267cd25bdad7df2383ea3425660b0d05054ebb", "hash" : "fa8e0c885c466e ... stripped out ... 5d9e17c02131f65", "username" : "test", "__v" : 0 }

**Comment by chaldon** [comment]
Can't reproduce. Please check that you have a latest DRE services deployed. I fixed this code at /lib/login/index.js at 
app.post('/api/v1/changepassword', function (req, res) {
...
    User.findOne({
        username: username
    }).select('_id salt hash username').exec( function (error, current_user) {

For some reason Moongoose started to request explicit list of fields propagated - '_id salt hash username'

**Comment by igiware** [comment]
now it changes passwd
